version: '3'
services:
 
  backend:
    build:
      context: ./restapi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - mynetwork

  # front end will go here once it is been added
  # frontend:
  #   build:
  #     context: ./path/to/your/react-app
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leaser_contract
      MYSQL_USER: leaser
      MYSQL_PASSWORD: leaser@contract
    volumes:
      - my-datavolume:/var/lib/mysql
    networks:
      - mynetwork
    ports:
      - "3306:3306"


volumes:
  my-datavolume:

networks:
  mynetwork: