version: '3'
services:
  backend:
    build:
      context: ./path/to/your/spring-boot-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database

  # front end will go here once it is been added
  # frontend:
  #   build:
  #     context: ./path/to/your/react-app
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leaser_contract
      MYSQL_USER: leaser
      MYSQL_PASSWORD: leaser@contract
    ports:
      - "3306:3306"